global:
  sim_duration: 100
  sim_seed: 1
  sim_output: "output.csv"

channel:
  channel_model:
    alfa: 2
    L0: 2

  interference_matrix:
  - SF12: [1, -23, -24, -25, -25, -25]
  - SF11: [-20, 1, -20, -21, -22, -22]
  - SF10: [-18, -17, 1, -17, -18, -19]
  - SF9:  [-15, -14, -13, 1, -13, -15]
  - SF8:  [-13, -13, -12, -11, 1, -11]
  - SF7:  [-9, -9, -9, -9, -8, 1]

end_device_default:
  traffic:
    mode: fixed
    period: 10
    t_init: 10
  tx_power_dBm: 14
  G_dB: 3
  SNR_min:
    - SF12: -20
    - SF11: -17.5
    - SF10: -15
    - SF9: -12.5
    - SF8: -10
    - SF7: -7.5

gateway_default:
  G_dB: 3
  NF_dB: 4
  SNR_min:
    - SF12: -20
    - SF11: -17.5
    - SF10: -15
    - SF9: -12.5
    - SF8: -10
    - SF7: -7.5

gateways:
- latitude: 42.1
  longitude: 0.84
  trackerid: name1
- latitude: 42.1
  longitude: 0.84
  trackerid: name2