global:
  sim_duration: 100
  sim_seed: 1
  sim_output: "output.csv"

channel_model:
  alpha: 2.32
  L0: 128.95
  SIR_thresholds: [[ 6.0, -16.0, -18.0, -19.0, -19.0, -20.0 ],
                  [ -24.0, 6.0, -20.0, -22.0, -22.0, -22.0 ],
                  [ -27.0, -27.0, 6.0, -23.0, -25.0, -25.0 ],
                  [ -30.0, -30.0, -30.0, 6.0, -26.0, -28.0 ],
                  [ -33.0, -33.0, -33.0, -33.0, 6.0, -29.0 ],
                  [ -36.0, -36.0, -36.0, -36.0, -36.0, 6.0 ]]

end_device_default:
  traffic:
    mode: fixed
    period: 10
    t_init: 10
    backoff: 0
  tx_power_dBm: 14
  antenna_gain_dBi: 3
  SNR_min:
    - SF12: -20
    - SF11: -17.5
    - SF10: -15
    - SF9: -12.5
    - SF8: -10
    - SF7: -7.5

gateway_default:
  antenna_gain_dBi: 3
  noise_figure_dB: 4
  SNR_min:
    - SF12: -20
    - SF11: -17.5
    - SF10: -15
    - SF9: -12.5
    - SF8: -10
    - SF7: -7.5

gateways:
  - trackerid: name1
    latitude: 42.9645653
    longitude: -2.63
  - trackerid: name2
    latitude: 42.9645653
    longitude: -2.6



end_devices:
  - trackerid: bb000019
    traffic:
      mode: fixed
      period: 4
      backoff: 0
  - trackerid: bb000008
    traffic:
      mode: fixed
      period: 4
      backoff: 0
